In [1]:
import numpy as np
import pandas as pd

In [2]:
embs = pd.read_parquet('embeddings_policies_Qwen3-4B_2026-03-05.parquet')

In [3]:
df = pd.read_parquet('clustered_policies_varying_gamma_2026-03-09.parquet', columns=['openalex_id', 'chunk_idx', 'policy_text', 'cluster_id_gamma_150'])

In [5]:
embs

,openalex_id,chunk_idx,domain,policy_type,actor,policy_text,embedding
0,W1000416519,0,URBAN,ECONOMIC,NATIONAL,Buyouts of property and structures as part of ...,"[-0.000351, 0.04614, 0.02902, 0.01041, -0.0021..."
1,W1000416519,0,URBAN,ECONOMIC,REGIONAL,Prioritization of parcels for buyouts to reduc...,"[-0.0004473, 0.03687, 0.008736, 0.01563, -0.00..."
2,W1000416519,0,NATURE,SPATIAL,NATIONAL,"Restoration of natural resources, including we...","[-0.0002345, -0.00078, -0.02588, -0.003849, -0..."
3,W1000416519,0,NATURE,SPATIAL,REGIONAL,Restoration of salmonid habitat in Sonoma Coun...,"[-0.0002744, 0.05298, -0.01653, 0.00801, -0.00..."
4,W1000416519,1,NATURE,ECONOMIC,NATIONAL,National Oceanic and Atmospheric Administratio...,"[-0.0001951, 0.02393, -0.00818, 0.06274, -0.00..."
...,...,...,...,...,...,...,...
1466022,W991832166,5,SOCIAL,REGULATORY,NATIONAL,Minority lists that fail to win preferential m...,"[-0.000576, 0.01172, -0.01033, 0.008766, -0.00..."
1466023,W991832166,5,SOCIAL,REGULATORY,NATIONAL,Minority MPs and spokespersons can found perma...,"[-0.0006123, 0.01182, -0.01665, 0.0316, -0.001..."
1466024,W991832166,5,SOCIAL,REGULATORY,NATIONAL,The new constitution places lesser importance ...,"[-0.0005507, 0.06198, 0.0279, 0.0116, -0.00221..."
1466025,W991832166,5,SOCIAL,REGULATORY,NATIONAL,The general line of internal minority policy h...,"[-0.0004122, 0.06134, 0.0211, 0.03714, -0.0014..."
1466026,W991832166,5,SOCIAL,REGULATORY,NATIONAL,"The ethnocultural definition of the nation, th...","[-0.0003965, 0.05423, 0.04614, -0.01776, -0.00..."

In [4]:
df

,openalex_id,chunk_idx,policy_text,cluster_id_gamma_150
0,W1000416519,0,Buyouts of property and structures as part of ...,0
1,W1000416519,0,Prioritization of parcels for buyouts to reduc...,0
2,W1000416519,0,"Restoration of natural resources, including we...",1
3,W1000416519,0,Restoration of salmonid habitat in Sonoma Coun...,2
4,W1000416519,1,National Oceanic and Atmospheric Administratio...,3
...,...,...,...,...
1466022,W991832166,5,Minority lists that fail to win preferential m...,684
1466023,W991832166,5,Minority MPs and spokespersons can found perma...,684
1466024,W991832166,5,The new constitution places lesser importance ...,684
1466025,W991832166,5,The general line of internal minority policy h...,684
1466026,W991832166,5,"The ethnocultural definition of the nation, th...",206

In [6]:
df['embedding'] = embs['embedding']

In [8]:
df = df.rename(columns={'policy_text': 'text', 'cluster_id_gamma_150': 'cluster_id'})

In [11]:
means = df.groupby('cluster_id')['embedding'].mean()

In [12]:
means

cluster_id
0       [-0.0002910907451923077, 0.03013548951048951, ...
1       [-0.000250694735738255, -0.004041701621923938,...
2       [-0.00030167897542317707, 0.0294189453125, -0....
3       [-0.00038320806962025315, 0.04956981803797468,...
4       [-0.0002656894095538312, -0.002339582322987391...
                              ...
3794    [-0.00028252601623535156, 0.0220184326171875, ...
3795    [-0.00013959407806396484, 0.0275421142578125, ...
3796    [-0.00040531158447265625, 0.057830810546875, -...
3797    [-0.00023102760314941406, 0.0168609619140625, ...
3798    [-0.0002696514129638672, 0.05120849609375, -0....
Name: embedding, Length: 3799, dtype: object

In [31]:
np.linalg.norm(means.iloc[0])

np.float64(0.7938511000469534)

In [36]:
nmeans = means / means.apply(np.linalg.norm)

## Delete small clusters
We don't reassign policies from deleted clusters to the cluster with the closest mean, as in many cases it's still very distant.

In [13]:
sizes = df['cluster_id'].value_counts()

In [16]:
small_cluster_ids = sizes[sizes <= 2].index.values

In [41]:
orphans = df[df['cluster_id'].isin(small_cluster_ids)]

In [43]:
orphemb = np.stack(orphans['embedding'])

In [48]:
npmeans = np.stack(nmeans)

In [83]:
sims = orphemb @ npmeans.T
sims.shape

(1330, 3799)

In [106]:
np.sort(sims, axis=1)[:, -2].mean() # there is usually no close cluster

np.float64(0.6676524328809926)

In [111]:
df = df.drop(orphans.index)

In [139]:
df.cluster_id.nunique()

2625

## Computing medoids

In [115]:
from tqdm.auto import tqdm

In [131]:
representatives = {}
for cluster_id, group in tqdm(df.groupby('cluster_id')):
    mu = nmeans.loc[cluster_id]
    embs = np.stack(group['embedding'])
    sims = embs @ mu
    closest_id = sims.argmax()
    closest = group.iloc[closest_id]
    representatives[cluster_id] = closest.name

  0%|          | 0/2625 [00:00<?, ?it/s]

In [140]:
df['representative'] = False

In [143]:
df.loc[representatives.values(), 'representative'] = True

In [146]:
df[df['representative'] == True]

,openalex_id,chunk_idx,text,cluster_id,embedding,representative
1232,W109263537,2,Involvement of stakeholders in the land-use pl...,587,"[-0.0002354, 0.01487, -0.02782, -0.00477, -0.0...",True
3132,W121033267,0,Integration of restorative justice approach an...,743,"[-0.0002925, 0.0415, -0.02556, 0.01381, -0.001...",True
3223,W121420035,2,"Recommendation for model refinement, particula...",1069,"[-0.000286, 0.0314, -0.02524, -0.02519, -0.001...",True
4366,W130298104,0,Dissemination of research findings to policy m...,1035,"[-0.0002059, 0.0461, -0.05304, 0.02115, -0.001...",True
4852,W135063704,1,Research on the effects of organic and convent...,1272,"[-0.0003061, 0.05875, -0.06082, -0.05737, -0.0...",True
...,...,...,...,...,...,...
1464148,W7104666906,2,Strengthen community engagement and empowermen...,2073,"[-0.0004404, 0.02258, -0.04062, -0.01403, -0.0...",True
1464187,W7104730991,2,Textile Strategy to promote sustainable practi...,393,"[-0.0003934, 0.03876, 0.00767, -0.01634, -0.00...",True
1464280,W7105117417,0,Promotion of climate-smart agricultural practi...,311,"[-0.000374, 0.04196, -0.04196, -0.04333, -0.00...",True
1464345,W7105603035,0,Government support for health-promoting EBIs f...,2231,"[-0.0004478, 0.0713, -0.03424, 0.0403, -0.0026...",True
1464851,W7105967719,2,Improved pastures,2008,"[-0.0002635, 0.0386, -0.01642, -0.0166, -0.001...",True

In [149]:
df.reset_index(drop=True)

,openalex_id,chunk_idx,text,cluster_id,embedding,representative
0,W1000416519,0,Buyouts of property and structures as part of ...,0,"[-0.000351, 0.04614, 0.02902, 0.01041, -0.0021...",False
1,W1000416519,0,Prioritization of parcels for buyouts to reduc...,0,"[-0.0004473, 0.03687, 0.008736, 0.01563, -0.00...",False
2,W1000416519,0,"Restoration of natural resources, including we...",1,"[-0.0002345, -0.00078, -0.02588, -0.003849, -0...",False
3,W1000416519,0,Restoration of salmonid habitat in Sonoma Coun...,2,"[-0.0002744, 0.05298, -0.01653, 0.00801, -0.00...",False
4,W1000416519,1,National Oceanic and Atmospheric Administratio...,3,"[-0.0001951, 0.02393, -0.00818, 0.06274, -0.00...",False
...,...,...,...,...,...,...
1464692,W991832166,5,Minority lists that fail to win preferential m...,684,"[-0.000576, 0.01172, -0.01033, 0.008766, -0.00...",False
1464693,W991832166,5,Minority MPs and spokespersons can found perma...,684,"[-0.0006123, 0.01182, -0.01665, 0.0316, -0.001...",False
1464694,W991832166,5,The new constitution places lesser importance ...,684,"[-0.0005507, 0.06198, 0.0279, 0.0116, -0.00221...",False
1464695,W991832166,5,The general line of internal minority policy h...,684,"[-0.0004122, 0.06134, 0.0211, 0.03714, -0.0014...",False
1464696,W991832166,5,"The ethnocultural definition of the nation, th...",206,"[-0.0003965, 0.05423, 0.04614, -0.01776, -0.00...",False

In [153]:
df = df.drop(columns='embedding')

In [155]:
df.reset_index(drop=True).to_parquet('clustered_policies_with_representatives_2026-03-10.parquet')

In [160]:
sizes

cluster_id
665     3223
1518    2897
21      2882
915     2849
839     2740
        ...
3794       1
3795       1
3796       1
3797       1
3798       1
Name: count, Length: 3799, dtype: int64

In [165]:
clust = df.loc[representatives.values()].merge(sizes, on='cluster_id')[['cluster_id', 'text', 'count']]
clust.to_csv('cluster_representatives_2026-03-10.csv', index=False)

In [121]:
a = 0
for cluster_id, rep in representatives.items():
    print(rep['text'])
    s = 0
    for i, row in df[df['cluster_id'] == cluster_id].iterrows():
        print('\t', row['text'])
        if s >= 10:
            break
        s += 1
    print('-'*40)
    if a >= 100:
        break
    a += 1

Insurance programs and tax incentives for flood risk
	 Buyouts of property and structures as part of FEMA’s overall risk reduction strategy
	 Prioritization of parcels for buyouts to reduce long-term risks and efficiently use limited governmental funds
	 FEMA’s Hazard Mitigation Grant Programs with obligated funds exceeding $700 million in 2013
	 Insurers should work with municipal governments and civil society to take an active role in preventing unnecessary losses by becoming involved in urban planning decisions.
	 Insurers could lobby for stricter provincial building codes for municipalities to reduce or prevent loss.
	 Insurers can educate consumer markets about the growing climate risk and provide information about which measures protect against storm damage.
	 Collaborating with government to protect against catastrophic losses.
	 Insurers could lobby the federal government to institute a government insurance program to re-insure the growing costs of catastrophic wildfires within these provinces.
	 Storm surge protection is one additional coverage option that consumers in Canada’s interior forests would benefit from.
	 Homeowners in Atlantic Canada will require some level of self-insurance to cope with the growing incidence and severity of coastal storms.
	 The careful application of hurricane deductibles to avoid cross-subsidization of risks.
----------------------------------------
Preserving natural lands for flood management
	 Restoration of natural resources, including wetland acreage and wildlife habitat, by removing structures from floodplains
	 Carefully analyse the potential impacts of drift wood transported during floods for infrastructures already located within the fluvial corridor
	 Creation of floodplain retention areas with a variety of stagnant freshwater habitats
	 Flood plains reserved for open space
	 Reclamation and redevelopment of flood plains as parks or recreational facilities
	 Creating new wetlands in the Mundeni Aru River Basin to reduce flood inundation extents
	 Forest restoration in the Mundeni Aru River Basin to reduce flood risks
	 Recreating wetlands in the downstream part of the Mundeni Aru River Basin to reduce flood risks
	 Respecting factors of natural floodplain forest dynamics such as erosion and accumulative effects of water flow during floods
	 Clear-felling of timber plantations should ideally be associated with rehabilitation and re-vegetation to avoid increasing the flood hazard.
	 Change from technical to ecohydrological thinking and an appreciation of the potential of natural floodplain ecosystems
----------------------------------------
Continuous monitoring of fishways to optimise restocking practices
	 Restoration of salmonid habitat in Sonoma County to align with biodiversity conservation objectives
	 Implementing more natural rearing conditions in hatcheries, such as adding structures like rocks and branches, underwater feeders, live prey items, overhead cover, and using alarm cues/predator odours to increase habitat complexity.
	 Using local strains for stocking hatchery-reared fish to eliminate population effects between hatchery-reared and wild individuals.
	 Releasing first generation (offspring of wild caught parents) fish to reduce the impact of inadvertent hatchery selection.
	 Stocking fish as eggs or young-of-year to minimize the effects of the unnatural hatchery environment on their behaviour by limiting hatchery exposure to a minimum.
	 Restoration of the Williamson River Delta to aid understanding of the effect on the dispersal of larval suckers and the ability of the project to increase retention of larvae in Upper Klamath Lake.
	 Increased PIT tagging of fish to improve survival estimates
	 Combining multiple fish releases in nearby areas into a singular release to improve survival estimates
	 Addition of the two Methow River and two Twisp River PTIS to estimate survival from different release groups over smaller sections of the Methow River
	 Estimating survival of the last two segments (McNary Dam to John Day Dam and John Day Dam to Bonneville Dam) based on hatchery releases (>25,000 tagged fish) due to the large number of tags that can be released
	 Increasing the Lower Methow River PTIS to at least 15 percent to improve survival estimates of all fish releases in the Methow River watershed
----------------------------------------
Increasing restoration funding
	 National Oceanic and Atmospheric Administration’s Restoration Center budget of $42 million for 2015
	 Invest $350,000 per year to recover the entire network and move it into good levels of condition
	 Government should provide resources to implement plans and agreements
	 Increasing investments in reclamation efforts and processing efficiencies
	 Received 9B regeneration funding
	 External funding from private sectors, enterprises, and the World Bank for restoration programs
	 Renegotiating the amount of funding for stations with accuracies that are not acceptable for the data uses with the data users.
	 EDA grant of at least $3.0 million for the renovation of the Fish Piers
	 More budget for renovations
	 Prioritize funding of agencies to achieve other recommendations.
	 Increase budgetary allocation for maintenance works at the National Theatre to enable effective maintenance.
----------------------------------------
Implementation of measures to mitigate the risk of floods in identified dangerous areas
	 Application of hazard mitigation funds to acquire properties or engage in restoration in areas with both high flood exposure and high conservation value
	 Avoid building any valuable structures in flood-prone areas
	 Application of appropriate safety measures to minimise risks associated with potential public access to open water zones
	 Implement appropriate measures to safeguard WSUD devices during the construction phase
	 Minimise risks associated with potential public access to open water zones with appropriate safety measures
	 Provision of a park that serves as a buffer against future sea level rise by ensuring buildings are located away from the areas at greatest risk of flooding and storm damage.
	 Reduce encroachment to highly sensitive areas such as the floodplain.
	 Controlling rapid urban development, particularly along the river and in floodplain areas
	 Differentiate protection levels in flood-prone areas to reduce vulnerability and enhance system robustness against extreme discharges.
	 Implement measures to limit the consequences of flooding, ensuring that the damage is reduced to below the recovery threshold.
	 Multiple-tiered flood risk management approach, which includes protection against flooding, spatial planning to limit flood impact, and emergency management to limit casualties.
----------------------------------------
Community planning for disaster risk management
	 Analyses like the one presented to strengthen the case for the application of hazard mitigation funds
	 Involvement of community members in disaster planning to foster community cohesion
	 National disaster management plans to deal with the impacts of cyclones, droughts, and disease outbreaks
	 National disaster management plans to deal with the impacts of cyclones, droughts, and disease outbreaks.
	 Linking climate change, disaster management and land use planning policies to deal with both mitigation and adaptation measures
	 Steps for reducing exposure and vulnerability to hazards
	 Development of disaster management plans by key stakeholders in the host economy
	 $4 billion program to mitigate natural disasters
	 Strategies originating from the community itself for disaster risk reduction
	 Vision 2021 initiative for inclusion of disaster risk reduction in development planning
	 Swiss adaptation strategy recently published by the government
----------------------------------------
Cap-and-trade system for carbon emissions
	 Additional case studies focusing on Los Angeles, Marin, Napa, and Monterey Counties
	 Trading of CO2 emission rights between Quebec and Ontario
	 Emissions caps
	 Emissions caps
	 Establish a global carbon market through cap-and-trade programs to reduce GHG emissions
	 Implementation of carbon emission limits, taxes, and credits
	 Comprehensive cap and trade legislation in the domestic economy
	 Economy-wide caps and enforceable goals for GHG reductions
	 Cap and trade system
	 Pure cap-and-trade systems with one alternative where we specified a price path.
	 SIP Call cap-and-trade program
----------------------------------------
Collection of social and economic data to enhance vulnerability assessments
	 Including a third index scoring socioeconomic vulnerability in buyout projects
	 Engage in mapping of ecological and socio-economic vulnerability to understand its distribution and identify hot spots, resilience, adaptive capacity and carry out regional case studies to better understand causes that shape vulnerability
	 Predictive models to reflect hazards associated with small-scale disasters for different groups
	 Use of stage damage function for quantitative assessment of both physical and economic vulnerability
	 Research covering the measurement and assessment of vulnerability of various damage categories (tangible and non-tangible) for risk assessments
	 Development of a spatial index using GIS to measure social vulnerability towards humanitarian crisis
	 Identification and mapping of governorates with greater susceptibility to humanitarian crisis for planning response-based needs
	 Development of policies and plans driven by context-specific underlying determinants of social vulnerability
	 Population maps to calculate the population at risk for assessment of prevailing mortality and morbidity rates
	 Disaggregation of data by urban and rural communities and by socio-economic setting to identify areas of greatest need and the most vulnerable populations.
	 Establish a vulnerability map of the catchment showing more vulnerable areas
----------------------------------------
Implementing appropriate coastal management strategies
	 Applying the proposed approach to other coastal states of the country
	 Integrated, long-term scenario for managing the silting up process in the IZC, considering socio-economic impacts on agriculture and tourism and recreation.
	 Town-planner’s attention should be drawn to the impact of man-made coastline
	 Coastal population pressure should be monitored
	 Specific coastal zone development strategies may be worked out towards the ultimate welfare of the coastal community.
	 Formulate suitable programmes for their redeployment and rehabilitation under the overall framework of the integrated coastal zone management within the coastal agro ecosystem
	 Region-wise Geographical Information System of the coastal agro-climatic zones for coastal zone management and development should be prepared in consultation with experts from capture and culture fisheries
	 States may consider addressing the inclusion of greenhouse gas mitigation requirements where development impacts coastal wetland habitats
	 Communication between local governmental bodies could establish an integrated management policy for the coast of False Bay
	 Sustainable and conscious use of coastal zones with a balance between protection and use, maintaining them as natural heritages
	 Elaborate coastal management programs aimed to preserve the San Blas landscape and the ecological, economic and cultural benefits that this system offers at local and regional levels
----------------------------------------
Targeted support programs for digitalization in the agricultural sector
	 More thorough investigation of ICT solutions for agriculture
	 Implementation of cost effective technologies in harsh agro climatic conditions
	 Policies affecting technology in agriculture
	 Use of geospatial technology to inform efficient rural agricultural development
	 Education of farmers to improve the utilization of computers and information services.
	 Use of digital maps for assessing and comparing the effectiveness of means of production and its profitability in agriculture
	 Collaboration between industry, financial and research institutes, and tertiary institutions to actualize the application of geo-informatics techniques in agricultural development
	 Investment in technology for transmitting timely information about price trends for agricultural products
	 Infrastructure development for access to isolated villages in Mamberamo Raya Regency
	 Establishment of an electronic information platform by LJSYN to record and share cultivation data among farmers' cooperatives and agribusinesses.
	 BIOGESTECA project (“Piattaforma di biotecnologie verdi e di tecniche gestionali per un sistema agricolo ad elevate sostenibilità ambientale”) funded by Regione Lombardia
----------------------------------------
Establishment of online learning platforms in remote areas
	 Better understanding of how e-learning affects travelling
	 Adapting online course design and entry criteria to accommodate the verbal ability of the target clientele, such as simplifying text material or incorporating more video and graphic presentations.
	 Maintaining equivalent content and grading standards for both classroom-based and online offerings, ensuring equivalent student selection criteria for both course types.
	 Advocacy plan to help students understand legitimate expectations from distance education (DE) and develop necessary skills for interaction, time management, and personality traits integration.
	 Utilize electronic media and social media to support education
	 Support for information exchange and other accompanying measures to develop and disseminate the necessary knowledge-base about online remote types of service innovation.
	 Distance learning and e-learning formats for training to capture participants unable to travel or spare time for traditional face-to-face training.
	 Blended learning option with e-learning and traditional face-to-face delivery at the GTRC in Port Talbot, South Wales to mitigate travelling inconvenience.
	 Blended learning, i.e. the thoughtful integration of complementary face-to-face and online learning approaches and technologies, such as group meetings with patients, support of a nurse in face-to-face contacts or through telephone, to improve patients’ motivation
	 Participation in online learning activities should be taken into account in grading to encourage participation.
	 Instructors and course designers should define strategies for management and usage of computer mediated communication tools and also for instructional design of the course.
----------------------------------------
Measures to reduce greenhouse gas emissions
	 Policy measures to realize global GHG reduction potentials
	 Implementation of policies which reduce greenhouse gas emissions and enhance sinks.
	 Measures to reduce greenhouse gas emissions
	 Making land use and other regulatory decisions that directly affect greenhouse gas emissions
	 Sector-specific greenhouse gas reduction goals
	 Limiting climate change to the extent possible by minimizing emissions and sequestering carbon
	 Take actions to accelerate moisture loss to mitigate the CO2 issue
	 Climate camps (direct action camps in places of high carbon emissions)
	 Global agreement to coordinate large-scale or small-scale actions to minimize the impacts of global climate changes
	 EPA's CL Program to recognize manufacturing practices that reduce GHG emissions
	 State programs to recognize manufacturing practices that reduce GHG emissions
----------------------------------------
Analysis of consumer perceptions and purchasing choices
	 Consumer behavior analysis to mitigate rebound effects
	 Future projects aim to develop intelligence from national retailers to help develop a system of data collection on consumer buying trends / product placement and branding
	 Use of experimental results and quantitative estimates in a partial market equilibrium model for ex ante estimation of labeling/recommendation policies to predict market reactions.
	 Recommendation to include budget reminders in CVM survey questions to simulate a realistic market setting and be consistent with consumer behavior and demand theory.
	 Universities together with research institutes such as the Louis Bolk institute to carry out consumer research to identify the market potential and relevant market segments for products from dam rearing systems.
	 Parallel improvements in variety and mixture choices
	 Using CF information in consumer purchase situations where the number of products is limited
	 Conduct further studies to verify demand and consumption patterns statistically
	 Conveying realistic expectations for the quality of used high-quality products
	 Companies can customize the products or information presented to consumers based on the users’ emotions, incorporating this study with recommendation systems.
	 Marketing analysis to create a match between consumers and supply side in the Milan's urban area
----------------------------------------
Development and improvement of ICT development policies
	 Include local, not ICT-based, electronic solutions in building design
	 Information technology (IT) to improve information flow in value streams to improve customer satisfaction in a profitable manner
	 Promotion of information and communication technologies (ICT) adoption in rural areas
	 Enhance rural women’s knowledge on ICT and capacity of ICT implementing through network or computer knowledge training
	 Improve rural women’s social capital and the ability of implementing ICT through a confraternity made up of rural females
	 ITS-based initiatives
	 Implementing a proper IT infrastructure to manage their information systems
	 Target specific areas in ICT reforms including enhancing employee skills and infrastructure improvements
	 Better inform the public—journalists as well as potential end users—about available ICT solutions, highlighting aspects such as ‘intuitive operability’ and ‘safety features’
	 Communication strategies should be adapted to ensure (i) a broader dissemination of ICT-related information to the general public that is (ii) appropriate to diminish technology-related negative emotions and (iii) optimally triggers positive emotions as well as the desire to try out the solution
	 Applying ICT actively rather than passively for adaptation, requiring permanent personnel responsible for the maintenance of ICT systems.
----------------------------------------
Increasing the share of renewable energy in electricity generation
	 Include large-scale renewable electricity production
	 Significant increase in geothermal and wind power over the medium to long-term
	 Changing energy mix towards renewables with less specific environmental implications
	 Carefully plan the transition from current electrical systems to 100% renewable, considering the storage system, electrical transport and transmission system, and other important aspects.
	 Procurement of 92% of total energy from renewable energy suppliers
	 Optimising and maximising use of renewable energy whether generated on-site or imported
	 Increasing social consciousness and accepted declarations for Electrical Power generated out of Renewable Energy Sources
	 The penetration of renewable energy technologies leads to a stabilization of global atmospheric CO2 concentrations at around 500 ppm
	 Generating an additional demand for renewable energies of the order of 10 % of the global energy supply to change the mitigation costs by increasing the demand for renewable energies.
	 Enhancing the ratio of renewable resources in the total energy consumption
	 Integration of renewable and clean energy resources into the total energy mix
----------------------------------------
Integration of renewable energy sources in buildings
	 Include small-scale renewable integration in buildings

In [129]:
repdf = pd.DataFrame(representatives).T
repdf

,openalex_id,chunk_idx,text,cluster_id,embedding
0,W3034226054,0,Insurance programs and tax incentives for floo...,0,"[-0.0002165, 0.03012, 0.01015, 0.01595, -0.001..."
1,W3137623305,0,Preserving natural lands for flood management,1,"[-0.000114, 0.011856, -0.02217, 0.008194, -0.0..."
2,W4224955221,1,Continuous monitoring of fishways to optimise ...,2,"[-0.0002165, 0.02953, -0.05716, 0.006554, -0.0..."
3,W4388022516,3,Increasing restoration funding,3,"[-0.000325, 0.05966, 0.00443, 0.01685, -0.0019..."
4,W2587122776,0,Implementation of measures to mitigate the ris...,4,"[-0.0001707, -0.01356, -0.02719, -0.01584, -0...."
...,...,...,...,...,...
3673,W4412189162,0,Normativas de gestión de riesgos hídricos para...,3673,"[-0.0001266, 0.00054, -0.01688, 0.00635, -0.00..."
3702,W4413790643,7,Investments in infrastructure directly address...,3702,"[-0.0003774, 0.02861, -0.01226, -0.01043, -0.0..."
3708,W4413291661,0,Target Environment-Specific Deterioration Mana...,3708,"[-0.000606, 0.03757, -0.00348, -0.04715, -0.00..."
3710,W4414896874,0,Equity-led policies,3710,"[-0.0002997, 0.05832, -0.00622, 0.03204, -0.00..."
3759,W4415018649,1,Implementing tailored support programs to sust...,3759,"[-0.0005116, 0.0641, -0.02136, -0.01878, -0.00..."

In [130]:
df.loc[repdf.index]

KeyError: '[175, 558, 1139, 2211] not in index'