In [1]:
import pandas as pd

In [2]:
gold = pd.read_parquet('gold_impact_direction.parquet')

In [7]:
gold.head()

,openalex_id,chunk_idx,text,policy,impact_category,impact,direction
0,W1490165506,60,approximately 30% of the young homeless popul...,[SOCIAL] [PARTICIPATORY] [NATIONAL] Introduce ...,Justice,distributional,positive
1,W1490165506,60,approximately 30% of the young homeless popul...,[SOCIAL] [SPATIAL] [NATIONAL] Provide exit opt...,Justice,distributional,positive
2,W153963444,2,"former experiences, is an important constitue...",[NATURE] [ECONOMIC] [REGIONAL] Prize-money for...,PlanetaryBoundary,biosphere_integrity,positive
3,W153963444,2,"former experiences, is an important constitue...",[NATURE] [ECONOMIC] [REGIONAL] Prize-money for...,PlanetaryBoundary,climate_change,unknown
4,W153963444,2,"former experiences, is an important constitue...",[NATURE] [ECONOMIC] [REGIONAL] Prize-money for...,Wellbeing,community,unknown

In [6]:
gold.impact_category.value_counts()

impact_category
Wellbeing            608
PlanetaryBoundary    446
Justice              307
Resource             232
Need                 140
Name: count, dtype: int64

In [8]:
gold.impact.value_counts()

impact
environment                       258
climate_change                    210
distributional                    185
biosphere_integrity               101
jobs                               97
procedural                         92
land_system_change                 81
nutrition                          80
income                             80
agricultural_land                  77
health                             73
community                          66
forests                            50
shelter_and_living_conditions      48
urban_land                         48
freshwater_use                     45
freshwater                         30
recognitional                      28
civic_engagement                   21
education                          12
wetlands                           11
introduction_of_novel_entities      9
safety                              9
fossil_fuels                        9
biomass                             4
housing                             4
marine_resources                    3
transitional                        2
Name: count, dtype: int64

In [10]:
gold

,openalex_id,chunk_idx,text,policy,impact_category,impact,direction
0,W1490165506,60,approximately 30% of the young homeless popul...,[SOCIAL] [PARTICIPATORY] [NATIONAL] Introduce ...,Justice,distributional,positive
1,W1490165506,60,approximately 30% of the young homeless popul...,[SOCIAL] [SPATIAL] [NATIONAL] Provide exit opt...,Justice,distributional,positive
2,W153963444,2,"former experiences, is an important constitue...",[NATURE] [ECONOMIC] [REGIONAL] Prize-money for...,PlanetaryBoundary,biosphere_integrity,positive
3,W153963444,2,"former experiences, is an important constitue...",[NATURE] [ECONOMIC] [REGIONAL] Prize-money for...,PlanetaryBoundary,climate_change,unknown
4,W153963444,2,"former experiences, is an important constitue...",[NATURE] [ECONOMIC] [REGIONAL] Prize-money for...,Wellbeing,community,unknown
...,...,...,...,...,...,...,...
1756,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,PlanetaryBoundary,climate_change,unknown
1757,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,Wellbeing,environment,unknown
1758,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,Wellbeing,income,unknown
1759,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,Need,nutrition,unknown
1760,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,Justice,procedural,positive

In [11]:
rename_dict = {
        'Resource': 'Natural Resources',
        'Wellbeing': 'Wellbeing',
        'Need': 'Human Needs',
        'PlanetaryBoundary': 'Planetary Boundaries',
        'Justice': 'Justice',
}
gold['impact_category'] = gold['impact_category'].map(rename_dict)
gold

,openalex_id,chunk_idx,text,policy,impact_category,impact,direction
0,W1490165506,60,approximately 30% of the young homeless popul...,[SOCIAL] [PARTICIPATORY] [NATIONAL] Introduce ...,Justice,distributional,positive
1,W1490165506,60,approximately 30% of the young homeless popul...,[SOCIAL] [SPATIAL] [NATIONAL] Provide exit opt...,Justice,distributional,positive
2,W153963444,2,"former experiences, is an important constitue...",[NATURE] [ECONOMIC] [REGIONAL] Prize-money for...,Planetary Boundaries,biosphere_integrity,positive
3,W153963444,2,"former experiences, is an important constitue...",[NATURE] [ECONOMIC] [REGIONAL] Prize-money for...,Planetary Boundaries,climate_change,unknown
4,W153963444,2,"former experiences, is an important constitue...",[NATURE] [ECONOMIC] [REGIONAL] Prize-money for...,Wellbeing,community,unknown
...,...,...,...,...,...,...,...
1756,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,Planetary Boundaries,climate_change,unknown
1757,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,Wellbeing,environment,unknown
1758,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,Wellbeing,income,unknown
1759,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,Human Needs,nutrition,unknown
1760,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,Justice,procedural,positive

In [16]:
gold["impact_dim"] = gold.apply(
    lambda row: f"{row['impact_category']} - {row['impact'].replace('_', ' ').capitalize()}",
    axis=1,
)

In [19]:
gold = gold.drop(columns=['impact_category', 'impact'])
gold

,openalex_id,chunk_idx,text,policy,direction,impact_dim
0,W1490165506,60,approximately 30% of the young homeless popul...,[SOCIAL] [PARTICIPATORY] [NATIONAL] Introduce ...,positive,Justice - Distributional
1,W1490165506,60,approximately 30% of the young homeless popul...,[SOCIAL] [SPATIAL] [NATIONAL] Provide exit opt...,positive,Justice - Distributional
2,W153963444,2,"former experiences, is an important constitue...",[NATURE] [ECONOMIC] [REGIONAL] Prize-money for...,positive,Planetary Boundaries - Biosphere integrity
3,W153963444,2,"former experiences, is an important constitue...",[NATURE] [ECONOMIC] [REGIONAL] Prize-money for...,unknown,Planetary Boundaries - Climate change
4,W153963444,2,"former experiences, is an important constitue...",[NATURE] [ECONOMIC] [REGIONAL] Prize-money for...,unknown,Wellbeing - Community
...,...,...,...,...,...,...
1756,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,unknown,Planetary Boundaries - Climate change
1757,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,unknown,Wellbeing - Environment
1758,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,unknown,Wellbeing - Income
1759,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,unknown,Human Needs - Nutrition
1760,W60052349,83,by farm and retail farm supply drivers relati...,[MOBILITY] [REGULATORY] [NATIONAL] National ex...,positive,Justice - Procedural

In [20]:
with open("IMPACT_DIRECTION_EXTRACTION_PROMPT.txt") as f:
    system_prompt = f.read().strip()

In [29]:
all_prompts = []
all_metadata = []
for row in gold.itertuples():
    prompt = f"{system_prompt}\n\nReference text:\n{row.text}\n\nPolicy: {row.policy}\nImpact Dimension: {row.impact_dim}\nImpact direction:"
    all_prompts.append(prompt)
    all_metadata.append({
        'openalex_id': row.openalex_id,
        'chunk_idx': int(row.chunk_idx),
        'row_id': int(row.Index),
        'impact_dim': row.impact_dim,
        'label': row.direction,
    })

In [45]:
import os
import json
from dotenv import load_dotenv
from openai import AsyncOpenAI, RateLimitError
import asyncio
load_dotenv()

True

In [36]:
client = AsyncOpenAI(
    base_url=os.getenv("GENERATION_API_URL"),
    api_key=os.getenv("SCW_SECRET_KEY"),
)

In [46]:
choices = ['positive', 'negative', 'neutral', 'unknown']
model = "mistral-small-3.2-24b-instruct-2506"
CONCURRENCY = 20

response_format = {
    "type": "json_schema",
    "json_schema": {
        "name": "impact_direction",
        "strict": True,
        "schema": {
            "type": "object",
            "properties": {
                "impact_direction": {"type": "string", "enum": choices}
            },
            "required": ["impact_direction"],
            "additionalProperties": False,
        },
    },
}

sem = asyncio.Semaphore(CONCURRENCY)


async def predict_one(prompt, meta, max_retries=8):
    delay = 5.0
    for attempt in range(max_retries):
        async with sem:
            try:
                response = await client.chat.completions.create(
                    model=model,
                    messages=[{"role": "user", "content": prompt}],
                    max_tokens=10,
                    temperature=0,
                    response_format=response_format,
                )
                raw = response.choices[0].message.content
                label = json.loads(raw)["impact_direction"]
                return meta | {"impact_direction": label}
            except RateLimitError:
                if attempt == max_retries - 1:
                    raise
                await asyncio.sleep(delay)
                delay *= 2

In [47]:
from tqdm.asyncio import tqdm_asyncio

async def predict_all():
    tasks = [predict_one(p, m) for p, m in zip(all_prompts, all_metadata)]
    return await tqdm_asyncio.gather(*tasks)

results = await predict_all()

100%|██████████| 1733/1733 [03:00<00:00,  9.60it/s]

In [50]:
res = pd.DataFrame(results)

In [51]:
from sklearn.metrics import classification_report

In [53]:
print(classification_report(res['label'], res['impact_direction'], zero_division=0))

              precision    recall  f1-score   support

    negative       0.29      0.38      0.33        39
     neutral       0.00      0.00      0.00        14
    positive       0.70      0.89      0.79       672
     unknown       0.93      0.73      0.82      1008

    accuracy                           0.78      1733
   macro avg       0.48      0.50      0.48      1733
weighted avg       0.82      0.78      0.79      1733